#!/usr/bin/env bash
# Aevrix Phase 24 configuration reload smoke test.
#
# Proves the reload path end to end against a live server:
#   * SIGHUP applies hot values (log level, timeouts) without a restart
#   * restart-only values (port, workers) are accepted but warned about
#   * a broken config is rejected and the running server keeps serving
#   * the /admin/reload-config + /admin/config endpoints work, are token
#     protected, and refuse path overrides outside the config directory
#   * the server still shuts down cleanly afterwards
#
# Usage:
#   ./smoke_reload.sh                # run everything
#   SMOKE_OUT=/tmp/x ./smoke_reload.sh
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
OUT="${SMOKE_OUT:-/tmp/aevrix-reload-smoke}"
PORT=18192
STALE_PORT=18193
TOKEN="smoke-secret"
CONF="$OUT/reload.conf"
LOG="$OUT/reload.log"
mkdir -p "$OUT"
cd "$REPO"

PASS=0
FAIL=0
SV=""

stop_server() {
    if [ -n "${SV:-}" ]; then
        kill -TERM "$SV" 2>/dev/null
        sleep 0.4
        kill -KILL "$SV" 2>/dev/null
        wait 2>/dev/null
        SV=""
    fi
    pkill -f "build/aevrix -c $CONF" 2>/dev/null
    sleep 0.2
}
trap stop_server EXIT

check() { # <name> <expected> <actual>
    if [ "$2" = "$3" ]; then
        echo "PASS $1: $2"
        PASS=$((PASS + 1))
    else
        echo "FAIL $1: expected '$2', got '$3'"
        FAIL=$((FAIL + 1))
    fi
}

check_grep() { # <name> <pattern> <file>
    local result
    result="$(grep -cE "$2" "$3" 2>/dev/null || true)"
    if [ "${result:-0}" -gt 0 ]; then
        echo "PASS $1: found /$2/ in $(basename "$3")"
        PASS=$((PASS + 1))
    else
        echo "FAIL $1: /$2/ not found in $(basename "$3")"
        FAIL=$((FAIL + 1))
    fi
}

gen_config() { # <log_level> <keep_alive_ms> <port> <workers> <admin_enabled>
    cat > "$CONF" <<EOF
# Aevrix Phase 24 reload smoke configuration (regenerated by the test)
host = 127.0.0.1
port = $3
workers = $4
document_root = public

header_timeout_ms = 10000
body_timeout_ms = 30000
keep_alive_timeout_ms = $2
write_timeout_ms = 30000

max_connections = 200
max_buffer_size = 65536
max_request_body = 1048576

log_level = $1
admin_api_enabled = $5
admin_token = $TOKEN
EOF
}

get_code() { # <url> [curl args...]
    local url="$1"; shift
    local code
    code="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 5 "$@" "$url" 2>/dev/null)"
    if [ -z "$code" ]; then
        code="000"  # Connection refused: the server is (as expected) not listening
    fi
    echo "$code"
}

get_body() { # <url> [curl args...]
    local url="$1"; shift
    curl -sS --max-time 5 "$@" "$url" 2>/dev/null
}

wait_ready() { # <port>
    for _ in $(seq 1 40); do
        if [ "$(get_code "http://127.0.0.1:$1/health")" = "200" ]; then
            return 0
        fi
        sleep 0.15
    done
    return 1
}

sighup() { kill -HUP "$SV" 2>/dev/null; sleep 0.6; }

echo "=== Phase 24 configuration reload smoke (port $PORT) ==="

# --- startup -----------------------------------------------------------------
gen_config info 5000 "$PORT" 2 true
./build/aevrix -c "$CONF" > "$LOG" 2>&1 &
SV=$!
if ! wait_ready "$PORT"; then
    echo "FAIL: server did not become ready on :$PORT"
    echo "--- log ---"
    cat "$LOG"
    exit 1
fi
echo "server up (pid $SV)"

check "health_baseline" "200" "$(get_code "http://127.0.0.1:$PORT/health")"
check_grep "sighup_wired" "SIGHUP configuration reload enabled" "$LOG"

# --- admin endpoints and authentication ---------------------------------------
check "admin_config_needs_token" "401" \
      "$(get_code "http://127.0.0.1:$PORT/admin/config")"
check "admin_config_wrong_token" "401" \
      "$(get_code "http://127.0.0.1:$PORT/admin/config" -H 'Authorization: Bearer nope')"
check "admin_config_authorized" "200" \
      "$(get_code "http://127.0.0.1:$PORT/admin/config" -H "Authorization: Bearer $TOKEN")"
body="$(get_body "http://127.0.0.1:$PORT/admin/config" -H "Authorization: Bearer $TOKEN")"
echo "$body" | grep -q '^generation=1$' \
    && { echo "PASS admin_config_generation: generation=1"; PASS=$((PASS + 1)); } \
    || { echo "FAIL admin_config_generation: $(echo "$body" | head -3)"; FAIL=$((FAIL + 1)); }

check "admin_reload_unauthorized" "401" \
      "$(get_code "http://127.0.0.1:$PORT/admin/reload-config" -X POST)"
check "admin_reload_path_guard" "400" \
      "$(get_code "http://127.0.0.1:$PORT/admin/reload-config" -X POST \
         -H "Authorization: Bearer $TOKEN" --data-binary '/etc/hostname')"

# --- SIGHUP: hot values --------------------------------------------------------
marker=$(wc -l < "$LOG")
gen_config debug 7000 "$PORT" 2 true
sighup
check_grep "sighup_hot_applied" "Config reload applied" "$LOG"
check_grep "sighup_hot_reports_keys" "takes effect immediately: keep_alive_timeout_ms,log_level" "$LOG"
check "sighup_hot_generation" "2" \
      "$(get_body "http://127.0.0.1:$PORT/admin/config" -H "Authorization: Bearer $TOKEN" \
         | sed -n 's/^generation=\([0-9]*\)$/\1/p')"
body="$(get_body "http://127.0.0.1:$PORT/admin/config" -H "Authorization: Bearer $TOKEN")"
echo "$body" | grep -q "Keep-alive timeout: 7000 ms" \
    && { echo "PASS sighup_hot_timeout_visible: keep-alive 7000 ms"; PASS=$((PASS + 1)); } \
    || { echo "FAIL sighup_hot_timeout_visible"; FAIL=$((FAIL + 1)); }
echo "$body" | grep -q "Log level: debug" \
    && { echo "PASS sighup_hot_log_level_visible: log_level debug"; PASS=$((PASS + 1)); } \
    || { echo "FAIL sighup_hot_log_level_visible"; FAIL=$((FAIL + 1)); }

# A DEBUG line may only appear after the reload: the level is pushed into the
# logger, it is not re-read from the config at startup.
get_code "http://127.0.0.1:$PORT/health" >/dev/null
if tail -n +"$((marker + 1))" "$LOG" | grep -q "handle_read_event called"; then
    echo "PASS sighup_hot_logger_live: DEBUG output after reload"
    PASS=$((PASS + 1))
else
    echo "FAIL sighup_hot_logger_live: no DEBUG output after reload"
    FAIL=$((FAIL + 1))
fi

# --- SIGHUP: restart-only values ----------------------------------------------
gen_config debug 7000 "$STALE_PORT" 3 true
sighup
check_grep "sighup_restart_warns" "needs a RESTART to take effect" "$LOG"
check_grep "sighup_restart_names_keys" "RESTART to take effect .running values unchanged.: port,workers" "$LOG"
check "sighup_restart_port_unchanged" "200" "$(get_code "http://127.0.0.1:$PORT/health")"
check "sighup_stale_port_not_open" "000" "$(get_code "http://127.0.0.1:$STALE_PORT/health")"

# --- SIGHUP: invalid config is rejected ---------------------------------------
gen_config info 5000 "$PORT" 0 true
sighup
check_grep "sighup_invalid_rejected" "config reload REJECTED" "$LOG"
check_grep "sighup_invalid_reason" "Invalid workers" "$LOG"
check "sighup_invalid_still_serving" "200" "$(get_code "http://127.0.0.1:$PORT/health")"

gen_config info 5000 "$PORT" 2 true
sighup
check "sighup_after_invalid_generation" "4" \
      "$(get_body "http://127.0.0.1:$PORT/admin/config" -H "Authorization: Bearer $TOKEN" \
         | sed -n 's/^generation=\([0-9]*\)$/\1/p')"

# --- admin POST reload --------------------------------------------------------
check "admin_reload_applies" "200" \
      "$(get_code "http://127.0.0.1:$PORT/admin/reload-config" -X POST \
         -H "Authorization: Bearer $TOKEN")"
body="$(get_body "http://127.0.0.1:$PORT/admin/reload-config" -X POST \
        -H "Authorization: Bearer $TOKEN")"
echo "$body" | grep -q '^reload: applied$' \
    && { echo "PASS admin_reload_body: reload: applied"; PASS=$((PASS + 1)); } \
    || { echo "FAIL admin_reload_body: $body"; FAIL=$((FAIL + 1)); }

# --- admin API disabled again -------------------------------------------------
gen_config info 5000 "$PORT" 2 false
sighup
check_grep "sighup_admin_disabled_applied" "admin_api_enabled: true -> false" "$LOG"
check "admin_config_hidden_when_disabled" "404" \
      "$(get_code "http://127.0.0.1:$PORT/admin/config" -H "Authorization: Bearer $TOKEN")"
check "health_after_admin_disabled" "200" "$(get_code "http://127.0.0.1:$PORT/health")"

# --- clean shutdown ------------------------------------------------------------
kill -TERM "$SV"
gone=1
for _ in $(seq 1 30); do
    if ! kill -0 "$SV" 2>/dev/null; then
        gone=0
        break
    fi
    sleep 0.2
done
check "clean_shutdown" "0" "$gone"
SV=""
trap - EXIT

echo
echo "RESULT: $PASS passed, $FAIL failed"
echo "--- server log (reload lines) ---"
grep -E "reload|RESTART|Log level|SIGHUP" "$LOG" | tail -12
[ "$FAIL" -eq 0 ]
